using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;

namespace MVCUIHelpers.IconsAndButtons.FamFamSprites
{
    public enum FamFamSpritesEnum
    {
        [Description("ss_accept")]
        accept,
        [Description("ss_add")]
        add,
        [Description("ss_anchor")]
        anchor,
        [Description("ss_application")]
        application,
        [Description("ss_application_add")]
        application_add,
        [Description("ss_application_cascade")]
        application_cascade,
        [Description("ss_application_delete")]
        application_delete,
        [Description("ss_application_double")]
        application_double,
        [Description("ss_application_edit")]
        application_edit,
        [Description("ss_application_error")]
        application_error,
        [Description("ss_application_form")]
        application_form,
        [Description("ss_application_form_add")]
        application_form_add,
        [Description("ss_application_form_delete")]
        application_form_delete,
        [Description("ss_application_form_edit")]
        application_form_edit,
        [Description("ss_application_form_magnify")]
        application_form_magnify,
        [Description("ss_application_get")]
        application_get,
        [Description("ss_application_go")]
        application_go,
        [Description("ss_application_home")]
        application_home,
        [Description("ss_application_key")]
        application_key,
        [Description("ss_application_lightning")]
        application_lightning,
        [Description("ss_application_link")]
        application_link,
        [Description("ss_application_osx")]
        application_osx,
        [Description("ss_application_osx_terminal")]
        application_osx_terminal,
        [Description("ss_application_put")]
        application_put,
        [Description("ss_application_side_boxes")]
        application_side_boxes,
        [Description("ss_application_side_contract")]
        application_side_contract,
        [Description("ss_application_side_expand")]
        application_side_expand,
        [Description("ss_application_side_list")]
        application_side_list,
        [Description("ss_application_side_tree")]
        application_side_tree,
        [Description("ss_application_split")]
        application_split,
        [Description("ss_application_tile_horizontal")]
        application_tile_horizontal,
        [Description("ss_application_tile_vertical")]
        application_tile_vertical,
        [Description("ss_application_view_columns")]
        application_view_columns,
        [Description("ss_application_view_detail")]
        application_view_detail,
        [Description("ss_application_view_gallery")]
        application_view_gallery,
        [Description("ss_application_view_icons")]
        application_view_icons,
        [Description("ss_application_view_list")]
        application_view_list,
        [Description("ss_application_view_tile")]
        application_view_tile,
        [Description("ss_application_xp")]
        application_xp,
        [Description("ss_application_xp_terminal")]
        application_xp_terminal,
        [Description("ss_arrow_branch")]
        arrow_branch,
        [Description("ss_arrow_divide")]
        arrow_divide,
        [Description("ss_arrow_down")]
        arrow_down,
        [Description("ss_arrow_in")]
        arrow_in,
        [Description("ss_arrow_inout")]
        arrow_inout,
        [Description("ss_arrow_join")]
        arrow_join,
        [Description("ss_arrow_left")]
        arrow_left,
        [Description("ss_arrow_merge")]
        arrow_merge,
        [Description("ss_arrow_out")]
        arrow_out,
        [Description("ss_arrow_redo")]
        arrow_redo,
        [Description("ss_arrow_refresh")]
        arrow_refresh,
        [Description("ss_arrow_refresh_small")]
        arrow_refresh_small,
        [Description("ss_arrow_right")]
        arrow_right,
        [Description("ss_arrow_rotate_anticlockwise")]
        arrow_rotate_anticlockwise,
        [Description("ss_arrow_rotate_clockwise")]
        arrow_rotate_clockwise,
        [Description("ss_arrow_switch")]
        arrow_switch,
        [Description("ss_arrow_turn_left")]
        arrow_turn_left,
        [Description("ss_arrow_turn_right")]
        arrow_turn_right,
        [Description("ss_arrow_undo")]
        arrow_undo,
        [Description("ss_arrow_up")]
        arrow_up,
        [Description("ss_asterisk_orange")]
        asterisk_orange,
        [Description("ss_asterisk_yellow")]
        asterisk_yellow,
        [Description("ss_attach")]
        attach,
        [Description("ss_award_star_add")]
        award_star_add,
        [Description("ss_award_star_bronze_1")]
        award_star_bronze_1,
        [Description("ss_award_star_bronze_2")]
        award_star_bronze_2,
        [Description("ss_award_star_bronze_3")]
        award_star_bronze_3,
        [Description("ss_award_star_delete")]
        award_star_delete,
        [Description("ss_award_star_gold_1")]
        award_star_gold_1,
        [Description("ss_award_star_gold_2")]
        award_star_gold_2,
        [Description("ss_award_star_gold_3")]
        award_star_gold_3,
        [Description("ss_award_star_silver_1")]
        award_star_silver_1,
        [Description("ss_award_star_silver_2")]
        award_star_silver_2,
        [Description("ss_award_star_silver_3")]
        award_star_silver_3,
        [Description("ss_basket")]
        basket,
        [Description("ss_basket_add")]
        basket_add,
        [Description("ss_basket_delete")]
        basket_delete,
        [Description("ss_basket_edit")]
        basket_edit,
        [Description("ss_basket_error")]
        basket_error,
        [Description("ss_basket_go")]
        basket_go,
        [Description("ss_basket_put")]
        basket_put,
        [Description("ss_basket_remove")]
        basket_remove,
        [Description("ss_bell")]
        bell,
        [Description("ss_bell_add")]
        bell_add,
        [Description("ss_bell_delete")]
        bell_delete,
        [Description("ss_bell_error")]
        bell_error,
        [Description("ss_bell_go")]
        bell_go,
        [Description("ss_bell_link")]
        bell_link,
        [Description("ss_bin")]
        bin,
        [Description("ss_bin_closed")]
        bin_closed,
        [Description("ss_bin_empty")]
        bin_empty,
        [Description("ss_bomb")]
        bomb,
        [Description("ss_book")]
        book,
        [Description("ss_book_add")]
        book_add,
        [Description("ss_book_addresses")]
        book_addresses,
        [Description("ss_book_delete")]
        book_delete,
        [Description("ss_book_edit")]
        book_edit,
        [Description("ss_book_error")]
        book_error,
        [Description("ss_book_go")]
        book_go,
        [Description("ss_book_key")]
        book_key,
        [Description("ss_book_link")]
        book_link,
        [Description("ss_book_next")]
        book_next,
        [Description("ss_book_open")]
        book_open,
        [Description("ss_book_previous")]
        book_previous,
        [Description("ss_box")]
        box,
        [Description("ss_brick")]
        brick,
        [Description("ss_brick_add")]
        brick_add,
        [Description("ss_brick_delete")]
        brick_delete,
        [Description("ss_brick_edit")]
        brick_edit,
        [Description("ss_brick_error")]
        brick_error,
        [Description("ss_brick_go")]
        brick_go,
        [Description("ss_brick_link")]
        brick_link,
        [Description("ss_bricks")]
        bricks,
        [Description("ss_briefcase")]
        briefcase,
        [Description("ss_bug")]
        bug,
        [Description("ss_bug_add")]
        bug_add,
        [Description("ss_bug_delete")]
        bug_delete,
        [Description("ss_bug_edit")]
        bug_edit,
        [Description("ss_bug_error")]
        bug_error,
        [Description("ss_bug_go")]
        bug_go,
        [Description("ss_bug_link")]
        bug_link,
        [Description("ss_building")]
        building,
        [Description("ss_building_add")]
        building_add,
        [Description("ss_building_delete")]
        building_delete,
        [Description("ss_building_edit")]
        building_edit,
        [Description("ss_building_error")]
        building_error,
        [Description("ss_building_go")]
        building_go,
        [Description("ss_building_key")]
        building_key,
        [Description("ss_building_link")]
        building_link,
        [Description("ss_bullet_add")]
        bullet_add,
        [Description("ss_bullet_arrow_bottom")]
        bullet_arrow_bottom,
        [Description("ss_bullet_arrow_down")]
        bullet_arrow_down,
        [Description("ss_bullet_arrow_top")]
        bullet_arrow_top,
        [Description("ss_bullet_arrow_up")]
        bullet_arrow_up,
        [Description("ss_bullet_black")]
        bullet_black,
        [Description("ss_bullet_blue")]
        bullet_blue,
        [Description("ss_bullet_delete")]
        bullet_delete,
        [Description("ss_bullet_disk")]
        bullet_disk,
        [Description("ss_bullet_error")]
        bullet_error,
        [Description("ss_bullet_feed")]
        bullet_feed,
        [Description("ss_bullet_go")]
        bullet_go,
        [Description("ss_bullet_green")]
        bullet_green,
        [Description("ss_bullet_key")]
        bullet_key,
        [Description("ss_bullet_orange")]
        bullet_orange,
        [Description("ss_bullet_picture")]
        bullet_picture,
        [Description("ss_bullet_pink")]
        bullet_pink,
        [Description("ss_bullet_purple")]
        bullet_purple,
        [Description("ss_bullet_red")]
        bullet_red,
        [Description("ss_bullet_star")]
        bullet_star,
        [Description("ss_bullet_toggle_minus")]
        bullet_toggle_minus,
        [Description("ss_bullet_toggle_plus")]
        bullet_toggle_plus,
        [Description("ss_bullet_white")]
        bullet_white,
        [Description("ss_bullet_wrench")]
        bullet_wrench,
        [Description("ss_bullet_yellow")]
        bullet_yellow,
        [Description("ss_cake")]
        cake,
        [Description("ss_calculator")]
        calculator,
        [Description("ss_calculator_add")]
        calculator_add,
        [Description("ss_calculator_delete")]
        calculator_delete,
        [Description("ss_calculator_edit")]
        calculator_edit,
        [Description("ss_calculator_error")]
        calculator_error,
        [Description("ss_calculator_link")]
        calculator_link,
        [Description("ss_calendar")]
        calendar,
        [Description("ss_calendar_add")]
        calendar_add,
        [Description("ss_calendar_delete")]
        calendar_delete,
        [Description("ss_calendar_edit")]
        calendar_edit,
        [Description("ss_calendar_link")]
        calendar_link,
        [Description("ss_calendar_view_day")]
        calendar_view_day,
        [Description("ss_calendar_view_month")]
        calendar_view_month,
        [Description("ss_calendar_view_week")]
        calendar_view_week,
        [Description("ss_camera")]
        camera,
        [Description("ss_camera_add")]
        camera_add,
        [Description("ss_camera_delete")]
        camera_delete,
        [Description("ss_camera_edit")]
        camera_edit,
        [Description("ss_camera_error")]
        camera_error,
        [Description("ss_camera_go")]
        camera_go,
        [Description("ss_camera_link")]
        camera_link,
        [Description("ss_camera_small")]
        camera_small,
        [Description("ss_cancel")]
        cancel,
        [Description("ss_car")]
        car,
        [Description("ss_car_add")]
        car_add,
        [Description("ss_car_delete")]
        car_delete,
        [Description("ss_cart")]
        cart,
        [Description("ss_cart_add")]
        cart_add,
        [Description("ss_cart_delete")]
        cart_delete,
        [Description("ss_cart_edit")]
        cart_edit,
        [Description("ss_cart_error")]
        cart_error,
        [Description("ss_cart_go")]
        cart_go,
        [Description("ss_cart_put")]
        cart_put,
        [Description("ss_cart_remove")]
        cart_remove,
        [Description("ss_cd")]
        cd,
        [Description("ss_cd_add")]
        cd_add,
        [Description("ss_cd_burn")]
        cd_burn,
        [Description("ss_cd_delete")]
        cd_delete,
        [Description("ss_cd_edit")]
        cd_edit,
        [Description("ss_cd_eject")]
        cd_eject,
        [Description("ss_cd_go")]
        cd_go,
        [Description("ss_chart_bar")]
        chart_bar,
        [Description("ss_chart_bar_add")]
        chart_bar_add,
        [Description("ss_chart_bar_delete")]
        chart_bar_delete,
        [Description("ss_chart_bar_edit")]
        chart_bar_edit,
        [Description("ss_chart_bar_error")]
        chart_bar_error,
        [Description("ss_chart_bar_link")]
        chart_bar_link,
        [Description("ss_chart_curve")]
        chart_curve,
        [Description("ss_chart_curve_add")]
        chart_curve_add,
        [Description("ss_chart_curve_delete")]
        chart_curve_delete,
        [Description("ss_chart_curve_edit")]
        chart_curve_edit,
        [Description("ss_chart_curve_error")]
        chart_curve_error,
        [Description("ss_chart_curve_go")]
        chart_curve_go,
        [Description("ss_chart_curve_link")]
        chart_curve_link,
        [Description("ss_chart_line")]
        chart_line,
        [Description("ss_chart_line_add")]
        chart_line_add,
        [Description("ss_chart_line_delete")]
        chart_line_delete,
        [Description("ss_chart_line_edit")]
        chart_line_edit,
        [Description("ss_chart_line_error")]
        chart_line_error,
        [Description("ss_chart_line_link")]
        chart_line_link,
        [Description("ss_chart_organisation")]
        chart_organisation,
        [Description("ss_chart_organisation_add")]
        chart_organisation_add,
        [Description("ss_chart_organisation_delete")]
        chart_organisation_delete,
        [Description("ss_chart_pie")]
        chart_pie,
        [Description("ss_chart_pie_add")]
        chart_pie_add,
        [Description("ss_chart_pie_delete")]
        chart_pie_delete,
        [Description("ss_chart_pie_edit")]
        chart_pie_edit,
        [Description("ss_chart_pie_error")]
        chart_pie_error,
        [Description("ss_chart_pie_link")]
        chart_pie_link,
        [Description("ss_clock")]
        clock,
        [Description("ss_clock_add")]
        clock_add,
        [Description("ss_clock_delete")]
        clock_delete,
        [Description("ss_clock_edit")]
        clock_edit,
        [Description("ss_clock_error")]
        clock_error,
        [Description("ss_clock_go")]
        clock_go,
        [Description("ss_clock_link")]
        clock_link,
        [Description("ss_clock_pause")]
        clock_pause,
        [Description("ss_clock_play")]
        clock_play,
        [Description("ss_clock_red")]
        clock_red,
        [Description("ss_clock_stop")]
        clock_stop,
        [Description("ss_cog")]
        cog,
        [Description("ss_cog_add")]
        cog_add,
        [Description("ss_cog_delete")]
        cog_delete,
        [Description("ss_cog_edit")]
        cog_edit,
        [Description("ss_cog_error")]
        cog_error,
        [Description("ss_cog_go")]
        cog_go,
        [Description("ss_coins")]
        coins,
        [Description("ss_coins_add")]
        coins_add,
        [Description("ss_coins_delete")]
        coins_delete,
        [Description("ss_color_swatch")]
        color_swatch,
        [Description("ss_color_wheel")]
        color_wheel,
        [Description("ss_comment")]
        comment,
        [Description("ss_comment_add")]
        comment_add,
        [Description("ss_comment_delete")]
        comment_delete,
        [Description("ss_comment_edit")]
        comment_edit,
        [Description("ss_comments")]
        comments,
        [Description("ss_comments_add")]
        comments_add,
        [Description("ss_comments_delete")]
        comments_delete,
        [Description("ss_compress")]
        compress,
        [Description("ss_computer")]
        computer,
        [Description("ss_computer_add")]
        computer_add,
        [Description("ss_computer_delete")]
        computer_delete,
        [Description("ss_computer_edit")]
        computer_edit,
        [Description("ss_computer_error")]
        computer_error,
        [Description("ss_computer_go")]
        computer_go,
        [Description("ss_computer_key")]
        computer_key,
        [Description("ss_computer_link")]
        computer_link,
        [Description("ss_connect")]
        connect,
        [Description("ss_contrast")]
        contrast,
        [Description("ss_contrast_decrease")]
        contrast_decrease,
        [Description("ss_contrast_high")]
        contrast_high,
        [Description("ss_contrast_increase")]
        contrast_increase,
        [Description("ss_contrast_low")]
        contrast_low,
        [Description("ss_control_eject")]
        control_eject,
        [Description("ss_control_eject_blue")]
        control_eject_blue,
        [Description("ss_control_end")]
        control_end,
        [Description("ss_control_end_blue")]
        control_end_blue,
        [Description("ss_control_equalizer")]
        control_equalizer,
        [Description("ss_control_equalizer_blue")]
        control_equalizer_blue,
        [Description("ss_control_fastforward")]
        control_fastforward,
        [Description("ss_control_fastforward_blue")]
        control_fastforward_blue,
        [Description("ss_control_pause")]
        control_pause,
        [Description("ss_control_pause_blue")]
        control_pause_blue,
        [Description("ss_control_play")]
        control_play,
        [Description("ss_control_play_blue")]
        control_play_blue,
        [Description("ss_control_repeat")]
        control_repeat,
        [Description("ss_control_repeat_blue")]
        control_repeat_blue,
        [Description("ss_control_rewind")]
        control_rewind,
        [Description("ss_control_rewind_blue")]
        control_rewind_blue,
        [Description("ss_control_start")]
        control_start,
        [Description("ss_control_start_blue")]
        control_start_blue,
        [Description("ss_control_stop")]
        control_stop,
        [Description("ss_control_stop_blue")]
        control_stop_blue,
        [Description("ss_controller")]
        controller,
        [Description("ss_controller_add")]
        controller_add,
        [Description("ss_controller_delete")]
        controller_delete,
        [Description("ss_controller_error")]
        controller_error,
        [Description("ss_creditcards")]
        creditcards,
        [Description("ss_cross")]
        cross,
        [Description("ss_css")]
        css,
        [Description("ss_css_add")]
        css_add,
        [Description("ss_css_delete")]
        css_delete,
        [Description("ss_css_go")]
        css_go,
        [Description("ss_css_valid")]
        css_valid,
        [Description("ss_cup")]
        cup,
        [Description("ss_cup_add")]
        cup_add,
        [Description("ss_cup_delete")]
        cup_delete,
        [Description("ss_cup_edit")]
        cup_edit,
        [Description("ss_cup_error")]
        cup_error,
        [Description("ss_cup_go")]
        cup_go,
        [Description("ss_cup_key")]
        cup_key,
        [Description("ss_cup_link")]
        cup_link,
        [Description("ss_cursor")]
        cursor,
        [Description("ss_cut")]
        cut,
        [Description("ss_cut_red")]
        cut_red,
        [Description("ss_database")]
        database,
        [Description("ss_database_add")]
        database_add,
        [Description("ss_database_connect")]
        database_connect,
        [Description("ss_database_delete")]
        database_delete,
        [Description("ss_database_edit")]
        database_edit,
        [Description("ss_database_error")]
        database_error,
        [Description("ss_database_gear")]
        database_gear,
        [Description("ss_database_go")]
        database_go,
        [Description("ss_database_key")]
        database_key,
        [Description("ss_database_lightning")]
        database_lightning,
        [Description("ss_database_link")]
        database_link,
        [Description("ss_database_refresh")]
        database_refresh,
        [Description("ss_database_save")]
        database_save,
        [Description("ss_database_table")]
        database_table,
        [Description("ss_date")]
        date,
        [Description("ss_date_add")]
        date_add,
        [Description("ss_date_delete")]
        date_delete,
        [Description("ss_date_edit")]
        date_edit,
        [Description("ss_date_error")]
        date_error,
        [Description("ss_date_go")]
        date_go,
        [Description("ss_date_link")]
        date_link,
        [Description("ss_date_magnify")]
        date_magnify,
        [Description("ss_date_next")]
        date_next,
        [Description("ss_date_previous")]
        date_previous,
        [Description("ss_delete")]
        delete,
        [Description("ss_disconnect")]
        disconnect,
        [Description("ss_disk")]
        disk,
        [Description("ss_disk_multiple")]
        disk_multiple,
        [Description("ss_door")]
        door,
        [Description("ss_door_in")]
        door_in,
        [Description("ss_door_open")]
        door_open,
        [Description("ss_door_out")]
        door_out,
        [Description("ss_drink")]
        drink,
        [Description("ss_drink_empty")]
        drink_empty,
        [Description("ss_drive")]
        drive,
        [Description("ss_drive_add")]
        drive_add,
        [Description("ss_drive_burn")]
        drive_burn,
        [Description("ss_drive_cd")]
        drive_cd,
        [Description("ss_drive_cd_empty")]
        drive_cd_empty,
        [Description("ss_drive_delete")]
        drive_delete,
        [Description("ss_drive_disk")]
        drive_disk,
        [Description("ss_drive_edit")]
        drive_edit,
        [Description("ss_drive_error")]
        drive_error,
        [Description("ss_drive_go")]
        drive_go,
        [Description("ss_drive_key")]
        drive_key,
        [Description("ss_drive_link")]
        drive_link,
        [Description("ss_drive_magnify")]
        drive_magnify,
        [Description("ss_drive_network")]
        drive_network,
        [Description("ss_drive_rename")]
        drive_rename,
        [Description("ss_drive_user")]
        drive_user,
        [Description("ss_drive_web")]
        drive_web,
        [Description("ss_dvd")]
        dvd,
        [Description("ss_dvd_add")]
        dvd_add,
        [Description("ss_dvd_delete")]
        dvd_delete,
        [Description("ss_dvd_edit")]
        dvd_edit,
        [Description("ss_dvd_error")]
        dvd_error,
        [Description("ss_dvd_go")]
        dvd_go,
        [Description("ss_dvd_key")]
        dvd_key,
        [Description("ss_dvd_link")]
        dvd_link,
        [Description("ss_email")]
        email,
        [Description("ss_email_add")]
        email_add,
        [Description("ss_email_attach")]
        email_attach,
        [Description("ss_email_delete")]
        email_delete,
        [Description("ss_email_edit")]
        email_edit,
        [Description("ss_email_error")]
        email_error,
        [Description("ss_email_go")]
        email_go,
        [Description("ss_email_link")]
        email_link,
        [Description("ss_email_open")]
        email_open,
        [Description("ss_email_open_image")]
        email_open_image,
        [Description("ss_emoticon_evilgrin")]
        emoticon_evilgrin,
        [Description("ss_emoticon_grin")]
        emoticon_grin,
        [Description("ss_emoticon_happy")]
        emoticon_happy,
        [Description("ss_emoticon_smile")]
        emoticon_smile,
        [Description("ss_emoticon_surprised")]
        emoticon_surprised,
        [Description("ss_emoticon_tongue")]
        emoticon_tongue,
        [Description("ss_emoticon_unhappy")]
        emoticon_unhappy,
        [Description("ss_emoticon_waii")]
        emoticon_waii,
        [Description("ss_emoticon_wink")]
        emoticon_wink,
        [Description("ss_error")]
        error,
        [Description("ss_error_add")]
        error_add,
        [Description("ss_error_delete")]
        error_delete,
        [Description("ss_error_go")]
        error_go,
        [Description("ss_exclamation")]
        exclamation,
        [Description("ss_eye")]
        eye,
        [Description("ss_feed")]
        feed,
        [Description("ss_feed_add")]
        feed_add,
        [Description("ss_feed_delete")]
        feed_delete,
        [Description("ss_feed_disk")]
        feed_disk,
        [Description("ss_feed_edit")]
        feed_edit,
        [Description("ss_feed_error")]
        feed_error,
        [Description("ss_feed_go")]
        feed_go,
        [Description("ss_feed_key")]
        feed_key,
        [Description("ss_feed_link")]
        feed_link,
        [Description("ss_feed_magnify")]
        feed_magnify,
        [Description("ss_female")]
        female,
        [Description("ss_film")]
        film,
        [Description("ss_film_add")]
        film_add,
        [Description("ss_film_delete")]
        film_delete,
        [Description("ss_film_edit")]
        film_edit,
        [Description("ss_film_error")]
        film_error,
        [Description("ss_film_go")]
        film_go,
        [Description("ss_film_key")]
        film_key,
        [Description("ss_film_link")]
        film_link,
        [Description("ss_film_save")]
        film_save,
        [Description("ss_find")]
        find,
        [Description("ss_flag_blue")]
        flag_blue,
        [Description("ss_flag_green")]
        flag_green,
        [Description("ss_flag_orange")]
        flag_orange,
        [Description("ss_flag_pink")]
        flag_pink,
        [Description("ss_flag_purple")]
        flag_purple,
        [Description("ss_flag_red")]
        flag_red,
        [Description("ss_flag_yellow")]
        flag_yellow,
        [Description("ss_folder")]
        folder,
        [Description("ss_folder_add")]
        folder_add,
        [Description("ss_folder_bell")]
        folder_bell,
        [Description("ss_folder_brick")]
        folder_brick,
        [Description("ss_folder_bug")]
        folder_bug,
        [Description("ss_folder_camera")]
        folder_camera,
        [Description("ss_folder_database")]
        folder_database,
        [Description("ss_folder_delete")]
        folder_delete,
        [Description("ss_folder_edit")]
        folder_edit,
        [Description("ss_folder_error")]
        folder_error,
        [Description("ss_folder_explore")]
        folder_explore,
        [Description("ss_folder_feed")]
        folder_feed,
        [Description("ss_folder_find")]
        folder_find,
        [Description("ss_folder_go")]
        folder_go,
        [Description("ss_folder_heart")]
        folder_heart,
        [Description("ss_folder_image")]
        folder_image,
        [Description("ss_folder_key")]
        folder_key,
        [Description("ss_folder_lightbulb")]
        folder_lightbulb,
        [Description("ss_folder_link")]
        folder_link,
        [Description("ss_folder_magnify")]
        folder_magnify,
        [Description("ss_folder_page")]
        folder_page,
        [Description("ss_folder_page_white")]
        folder_page_white,
        [Description("ss_folder_palette")]
        folder_palette,
        [Description("ss_folder_picture")]
        folder_picture,
        [Description("ss_folder_star")]
        folder_star,
        [Description("ss_folder_table")]
        folder_table,
        [Description("ss_folder_user")]
        folder_user,
        [Description("ss_folder_wrench")]
        folder_wrench,
        [Description("ss_font")]
        font,
        [Description("ss_font_add")]
        font_add,
        [Description("ss_font_delete")]
        font_delete,
        [Description("ss_font_go")]
        font_go,
        [Description("ss_group")]
        group,
        [Description("ss_group_add")]
        group_add,
        [Description("ss_group_delete")]
        group_delete,
        [Description("ss_group_edit")]
        group_edit,
        [Description("ss_group_error")]
        group_error,
        [Description("ss_group_gear")]
        group_gear,
        [Description("ss_group_go")]
        group_go,
        [Description("ss_group_key")]
        group_key,
        [Description("ss_group_link")]
        group_link,
        [Description("ss_heart")]
        heart,
        [Description("ss_heart_add")]
        heart_add,
        [Description("ss_heart_delete")]
        heart_delete,
        [Description("ss_help")]
        help,
        [Description("ss_hourglass")]
        hourglass,
        [Description("ss_hourglass_add")]
        hourglass_add,
        [Description("ss_hourglass_delete")]
        hourglass_delete,
        [Description("ss_hourglass_go")]
        hourglass_go,
        [Description("ss_hourglass_link")]
        hourglass_link,
        [Description("ss_house")]
        house,
        [Description("ss_house_go")]
        house_go,
        [Description("ss_house_link")]
        house_link,
        [Description("ss_html")]
        html,
        [Description("ss_html_add")]
        html_add,
        [Description("ss_html_delete")]
        html_delete,
        [Description("ss_html_go")]
        html_go,
        [Description("ss_html_valid")]
        html_valid,
        [Description("ss_image")]
        image,
        [Description("ss_image_add")]
        image_add,
        [Description("ss_image_delete")]
        image_delete,
        [Description("ss_image_edit")]
        image_edit,
        [Description("ss_image_link")]
        image_link,
        [Description("ss_images")]
        images,
        [Description("ss_information")]
        information,
        [Description("ss_ipod")]
        ipod,
        [Description("ss_ipod_cast")]
        ipod_cast,
        [Description("ss_ipod_cast_add")]
        ipod_cast_add,
        [Description("ss_ipod_cast_delete")]
        ipod_cast_delete,
        [Description("ss_ipod_sound")]
        ipod_sound,
        [Description("ss_joystick")]
        joystick,
        [Description("ss_joystick_add")]
        joystick_add,
        [Description("ss_joystick_delete")]
        joystick_delete,
        [Description("ss_joystick_error")]
        joystick_error,
        [Description("ss_key")]
        key,
        [Description("ss_key_add")]
        key_add,
        [Description("ss_key_delete")]
        key_delete,
        [Description("ss_key_go")]
        key_go,
        [Description("ss_keyboard")]
        keyboard,
        [Description("ss_keyboard_add")]
        keyboard_add,
        [Description("ss_keyboard_delete")]
        keyboard_delete,
        [Description("ss_keyboard_magnify")]
        keyboard_magnify,
        [Description("ss_layers")]
        layers,
        [Description("ss_layout")]
        layout,
        [Description("ss_layout_add")]
        layout_add,
        [Description("ss_layout_content")]
        layout_content,
        [Description("ss_layout_delete")]
        layout_delete,
        [Description("ss_layout_edit")]
        layout_edit,
        [Description("ss_layout_error")]
        layout_error,
        [Description("ss_layout_header")]
        layout_header,
        [Description("ss_layout_link")]
        layout_link,
        [Description("ss_layout_sidebar")]
        layout_sidebar,
        [Description("ss_lightbulb")]
        lightbulb,
        [Description("ss_lightbulb_add")]
        lightbulb_add,
        [Description("ss_lightbulb_delete")]
        lightbulb_delete,
        [Description("ss_lightbulb_off")]
        lightbulb_off,
        [Description("ss_lightning")]
        lightning,
        [Description("ss_lightning_add")]
        lightning_add,
        [Description("ss_lightning_delete")]
        lightning_delete,
        [Description("ss_lightning_go")]
        lightning_go,
        [Description("ss_link")]
        link,
        [Description("ss_link_add")]
        link_add,
        [Description("ss_link_break")]
        link_break,
        [Description("ss_link_delete")]
        link_delete,
        [Description("ss_link_edit")]
        link_edit,
        [Description("ss_link_error")]
        link_error,
        [Description("ss_link_go")]
        link_go,
        [Description("ss_lock")]
        Lock,
        [Description("ss_lock_add")]
        lock_add,
        [Description("ss_lock_break")]
        lock_break,
        [Description("ss_lock_delete")]
        lock_delete,
        [Description("ss_lock_edit")]
        lock_edit,
        [Description("ss_lock_go")]
        lock_go,
        [Description("ss_lock_open")]
        lock_open,
        [Description("ss_lorry")]
        lorry,
        [Description("ss_lorry_add")]
        lorry_add,
        [Description("ss_lorry_delete")]
        lorry_delete,
        [Description("ss_lorry_error")]
        lorry_error,
        [Description("ss_lorry_flatbed")]
        lorry_flatbed,
        [Description("ss_lorry_go")]
        lorry_go,
        [Description("ss_lorry_link")]
        lorry_link,
        [Description("ss_magifier_zoom_out")]
        magifier_zoom_out,
        [Description("ss_magnifier")]
        magnifier,
        [Description("ss_magnifier_zoom_in")]
        magnifier_zoom_in,
        [Description("ss_male")]
        male,
        [Description("ss_map")]
        map,
        [Description("ss_map_add")]
        map_add,
        [Description("ss_map_delete")]
        map_delete,
        [Description("ss_map_edit")]
        map_edit,
        [Description("ss_map_go")]
        map_go,
        [Description("ss_map_magnify")]
        map_magnify,
        [Description("ss_medal_bronze_1")]
        medal_bronze_1,
        [Description("ss_medal_bronze_2")]
        medal_bronze_2,
        [Description("ss_medal_bronze_3")]
        medal_bronze_3,
        [Description("ss_medal_bronze_add")]
        medal_bronze_add,
        [Description("ss_medal_bronze_delete")]
        medal_bronze_delete,
        [Description("ss_medal_gold_1")]
        medal_gold_1,
        [Description("ss_medal_gold_2")]
        medal_gold_2,
        [Description("ss_medal_gold_3")]
        medal_gold_3,
        [Description("ss_medal_gold_add")]
        medal_gold_add,
        [Description("ss_medal_gold_delete")]
        medal_gold_delete,
        [Description("ss_medal_silver_1")]
        medal_silver_1,
        [Description("ss_medal_silver_2")]
        medal_silver_2,
        [Description("ss_medal_silver_3")]
        medal_silver_3,
        [Description("ss_medal_silver_add")]
        medal_silver_add,
        [Description("ss_medal_silver_delete")]
        medal_silver_delete,
        [Description("ss_money")]
        money,
        [Description("ss_money_add")]
        money_add,
        [Description("ss_money_delete")]
        money_delete,
        [Description("ss_money_dollar")]
        money_dollar,
        [Description("ss_money_euro")]
        money_euro,
        [Description("ss_money_pound")]
        money_pound,
        [Description("ss_money_yen")]
        money_yen,
        [Description("ss_monitor")]
        monitor,
        [Description("ss_monitor_add")]
        monitor_add,
        [Description("ss_monitor_delete")]
        monitor_delete,
        [Description("ss_monitor_edit")]
        monitor_edit,
        [Description("ss_monitor_error")]
        monitor_error,
        [Description("ss_monitor_go")]
        monitor_go,
        [Description("ss_monitor_lightning")]
        monitor_lightning,
        [Description("ss_monitor_link")]
        monitor_link,
        [Description("ss_mouse")]
        mouse,
        [Description("ss_mouse_add")]
        mouse_add,
        [Description("ss_mouse_delete")]
        mouse_delete,
        [Description("ss_mouse_error")]
        mouse_error,
        [Description("ss_music")]
        music,
        [Description("ss_new")]
        New,
        [Description("ss_newspaper")]
        newspaper,
        [Description("ss_newspaper_add")]
        newspaper_add,
        [Description("ss_newspaper_delete")]
        newspaper_delete,
        [Description("ss_newspaper_go")]
        newspaper_go,
        [Description("ss_newspaper_link")]
        newspaper_link,
        [Description("ss_note")]
        note,
        [Description("ss_note_add")]
        note_add,
        [Description("ss_note_delete")]
        note_delete,
        [Description("ss_note_edit")]
        note_edit,
        [Description("ss_note_error")]
        note_error,
        [Description("ss_note_go")]
        note_go,
        [Description("ss_overlays")]
        overlays,
        [Description("ss_package")]
        package,
        [Description("ss_package_add")]
        package_add,
        [Description("ss_package_delete")]
        package_delete,
        [Description("ss_package_go")]
        package_go,
        [Description("ss_package_green")]
        package_green,
        [Description("ss_package_link")]
        package_link,
        [Description("ss_page")]
        page,
        [Description("ss_page_add")]
        page_add,
        [Description("ss_page_attach")]
        page_attach,
        [Description("ss_page_code")]
        page_code,
        [Description("ss_page_copy")]
        page_copy,
        [Description("ss_page_delete")]
        page_delete,
        [Description("ss_page_edit")]
        page_edit,
        [Description("ss_page_error")]
        page_error,
        [Description("ss_page_excel")]
        page_excel,
        [Description("ss_page_find")]
        page_find,
        [Description("ss_page_gear")]
        page_gear,
        [Description("ss_page_go")]
        page_go,
        [Description("ss_page_green")]
        page_green,
        [Description("ss_page_key")]
        page_key,
        [Description("ss_page_lightning")]
        page_lightning,
        [Description("ss_page_link")]
        page_link,
        [Description("ss_page_paintbrush")]
        page_paintbrush,
        [Description("ss_page_paste")]
        page_paste,
        [Description("ss_page_red")]
        page_red,
        [Description("ss_page_refresh")]
        page_refresh,
        [Description("ss_page_save")]
        page_save,
        [Description("ss_page_white")]
        page_white,
        [Description("ss_page_white_acrobat")]
        page_white_acrobat,
        [Description("ss_page_white_actionscript")]
        page_white_actionscript,
        [Description("ss_page_white_add")]
        page_white_add,
        [Description("ss_page_white_c")]
        page_white_c,
        [Description("ss_page_white_camera")]
        page_white_camera,
        [Description("ss_page_white_cd")]
        page_white_cd,
        [Description("ss_page_white_code")]
        page_white_code,
        [Description("ss_page_white_code_red")]
        page_white_code_red,
        [Description("ss_page_white_coldfusion")]
        page_white_coldfusion,
        [Description("ss_page_white_compressed")]
        page_white_compressed,
        [Description("ss_page_white_copy")]
        page_white_copy,
        [Description("ss_page_white_cplusplus")]
        page_white_cplusplus,
        [Description("ss_page_white_csharp")]
        page_white_csharp,
        [Description("ss_page_white_cup")]
        page_white_cup,
        [Description("ss_page_white_database")]
        page_white_database,
        [Description("ss_page_white_delete")]
        page_white_delete,
        [Description("ss_page_white_dvd")]
        page_white_dvd,
        [Description("ss_page_white_edit")]
        page_white_edit,
        [Description("ss_page_white_error")]
        page_white_error,
        [Description("ss_page_white_excel")]
        page_white_excel,
        [Description("ss_page_white_find")]
        page_white_find,
        [Description("ss_page_white_flash")]
        page_white_flash,
        [Description("ss_page_white_freehand")]
        page_white_freehand,
        [Description("ss_page_white_gear")]
        page_white_gear,
        [Description("ss_page_white_get")]
        page_white_get,
        [Description("ss_page_white_go")]
        page_white_go,
        [Description("ss_page_white_h")]
        page_white_h,
        [Description("ss_page_white_horizontal")]
        page_white_horizontal,
        [Description("ss_page_white_key")]
        page_white_key,
        [Description("ss_page_white_lightning")]
        page_white_lightning,
        [Description("ss_page_white_link")]
        page_white_link,
        [Description("ss_page_white_magnify")]
        page_white_magnify,
        [Description("ss_page_white_medal")]
        page_white_medal,
        [Description("ss_page_white_office")]
        page_white_office,
        [Description("ss_page_white_paint")]
        page_white_paint,
        [Description("ss_page_white_paintbrush")]
        page_white_paintbrush,
        [Description("ss_page_white_paste")]
        page_white_paste,
        [Description("ss_page_white_php")]
        page_white_php,
        [Description("ss_page_white_picture")]
        page_white_picture,
        [Description("ss_page_white_powerpoint")]
        page_white_powerpoint,
        [Description("ss_page_white_put")]
        page_white_put,
        [Description("ss_page_white_ruby")]
        page_white_ruby,
        [Description("ss_page_white_stack")]
        page_white_stack,
        [Description("ss_page_white_star")]
        page_white_star,
        [Description("ss_page_white_swoosh")]
        page_white_swoosh,
        [Description("ss_page_white_text")]
        page_white_text,
        [Description("ss_page_white_text_width")]
        page_white_text_width,
        [Description("ss_page_white_tux")]
        page_white_tux,
        [Description("ss_page_white_vector")]
        page_white_vector,
        [Description("ss_page_white_visualstudio")]
        page_white_visualstudio,
        [Description("ss_page_white_width")]
        page_white_width,
        [Description("ss_page_white_word")]
        page_white_word,
        [Description("ss_page_white_world")]
        page_white_world,
        [Description("ss_page_white_wrench")]
        page_white_wrench,
        [Description("ss_page_white_zip")]
        page_white_zip,
        [Description("ss_page_word")]
        page_word,
        [Description("ss_page_world")]
        page_world,
        [Description("ss_paintbrush")]
        paintbrush,
        [Description("ss_paintcan")]
        paintcan,
        [Description("ss_palette")]
        palette,
        [Description("ss_paste_plain")]
        paste_plain,
        [Description("ss_paste_word")]
        paste_word,
        [Description("ss_pencil")]
        pencil,
        [Description("ss_pencil_add")]
        pencil_add,
        [Description("ss_pencil_delete")]
        pencil_delete,
        [Description("ss_pencil_go")]
        pencil_go,
        [Description("ss_phone")]
        phone,
        [Description("ss_phone_add")]
        phone_add,
        [Description("ss_phone_delete")]
        phone_delete,
        [Description("ss_phone_sound")]
        phone_sound,
        [Description("ss_photo")]
        photo,
        [Description("ss_photo_add")]
        photo_add,
        [Description("ss_photo_delete")]
        photo_delete,
        [Description("ss_photo_link")]
        photo_link,
        [Description("ss_photos")]
        photos,
        [Description("ss_picture")]
        picture,
        [Description("ss_picture_add")]
        picture_add,
        [Description("ss_picture_delete")]
        picture_delete,
        [Description("ss_picture_edit")]
        picture_edit,
        [Description("ss_picture_empty")]
        picture_empty,
        [Description("ss_picture_error")]
        picture_error,
        [Description("ss_picture_go")]
        picture_go,
        [Description("ss_picture_key")]
        picture_key,
        [Description("ss_picture_link")]
        picture_link,
        [Description("ss_picture_save")]
        picture_save,
        [Description("ss_pictures")]
        pictures,
        [Description("ss_pilcrow")]
        pilcrow,
        [Description("ss_pill")]
        pill,
        [Description("ss_pill_add")]
        pill_add,
        [Description("ss_pill_delete")]
        pill_delete,
        [Description("ss_pill_go")]
        pill_go,
        [Description("ss_plugin")]
        plugin,
        [Description("ss_plugin_add")]
        plugin_add,
        [Description("ss_plugin_delete")]
        plugin_delete,
        [Description("ss_plugin_disabled")]
        plugin_disabled,
        [Description("ss_plugin_edit")]
        plugin_edit,
        [Description("ss_plugin_error")]
        plugin_error,
        [Description("ss_plugin_go")]
        plugin_go,
        [Description("ss_plugin_link")]
        plugin_link,
        [Description("ss_printer")]
        printer,
        [Description("ss_printer_add")]
        printer_add,
        [Description("ss_printer_delete")]
        printer_delete,
        [Description("ss_printer_empty")]
        printer_empty,
        [Description("ss_printer_error")]
        printer_error,
        [Description("ss_rainbow")]
        rainbow,
        [Description("ss_report")]
        report,
        [Description("ss_report_add")]
        report_add,
        [Description("ss_report_delete")]
        report_delete,
        [Description("ss_report_disk")]
        report_disk,
        [Description("ss_report_edit")]
        report_edit,
        [Description("ss_report_go")]
        report_go,
        [Description("ss_report_key")]
        report_key,
        [Description("ss_report_link")]
        report_link,
        [Description("ss_report_magnify")]
        report_magnify,
        [Description("ss_report_picture")]
        report_picture,
        [Description("ss_report_user")]
        report_user,
        [Description("ss_report_word")]
        report_word,
        [Description("ss_resultset_first")]
        resultset_first,
        [Description("ss_resultset_last")]
        resultset_last,
        [Description("ss_resultset_next")]
        resultset_next,
        [Description("ss_resultset_previous")]
        resultset_previous,
        [Description("ss_rosette")]
        rosette,
        [Description("ss_rss")]
        rss,
        [Description("ss_rss_add")]
        rss_add,
        [Description("ss_rss_delete")]
        rss_delete,
        [Description("ss_rss_go")]
        rss_go,
        [Description("ss_rss_valid")]
        rss_valid,
        [Description("ss_ruby")]
        ruby,
        [Description("ss_ruby_add")]
        ruby_add,
        [Description("ss_ruby_delete")]
        ruby_delete,
        [Description("ss_ruby_gear")]
        ruby_gear,
        [Description("ss_ruby_get")]
        ruby_get,
        [Description("ss_ruby_go")]
        ruby_go,
        [Description("ss_ruby_key")]
        ruby_key,
        [Description("ss_ruby_link")]
        ruby_link,
        [Description("ss_ruby_put")]
        ruby_put,
        [Description("ss_script")]
        script,
        [Description("ss_script_add")]
        script_add,
        [Description("ss_script_code")]
        script_code,
        [Description("ss_script_code_red")]
        script_code_red,
        [Description("ss_script_delete")]
        script_delete,
        [Description("ss_script_edit")]
        script_edit,
        [Description("ss_script_error")]
        script_error,
        [Description("ss_script_gear")]
        script_gear,
        [Description("ss_script_go")]
        script_go,
        [Description("ss_script_key")]
        script_key,
        [Description("ss_script_lightning")]
        script_lightning,
        [Description("ss_script_link")]
        script_link,
        [Description("ss_script_palette")]
        script_palette,
        [Description("ss_script_save")]
        script_save,
        [Description("ss_server")]
        server,
        [Description("ss_server_add")]
        server_add,
        [Description("ss_server_chart")]
        server_chart,
        [Description("ss_server_compressed")]
        server_compressed,
        [Description("ss_server_connect")]
        server_connect,
        [Description("ss_server_database")]
        server_database,
        [Description("ss_server_delete")]
        server_delete,
        [Description("ss_server_edit")]
        server_edit,
        [Description("ss_server_error")]
        server_error,
        [Description("ss_server_go")]
        server_go,
        [Description("ss_server_key")]
        server_key,
        [Description("ss_server_lightning")]
        server_lightning,
        [Description("ss_server_link")]
        server_link,
        [Description("ss_server_uncompressed")]
        server_uncompressed,
        [Description("ss_shading")]
        shading,
        [Description("ss_shape_align_bottom")]
        shape_align_bottom,
        [Description("ss_shape_align_center")]
        shape_align_center,
        [Description("ss_shape_align_left")]
        shape_align_left,
        [Description("ss_shape_align_middle")]
        shape_align_middle,
        [Description("ss_shape_align_right")]
        shape_align_right,
        [Description("ss_shape_align_top")]
        shape_align_top,
        [Description("ss_shape_flip_horizontal")]
        shape_flip_horizontal,
        [Description("ss_shape_flip_vertical")]
        shape_flip_vertical,
        [Description("ss_shape_group")]
        shape_group,
        [Description("ss_shape_handles")]
        shape_handles,
        [Description("ss_shape_move_back")]
        shape_move_back,
        [Description("ss_shape_move_backwards")]
        shape_move_backwards,
        [Description("ss_shape_move_forwards")]
        shape_move_forwards,
        [Description("ss_shape_move_front")]
        shape_move_front,
        [Description("ss_shape_rotate_anticlockwise")]
        shape_rotate_anticlockwise,
        [Description("ss_shape_rotate_clockwise")]
        shape_rotate_clockwise,
        [Description("ss_shape_square")]
        shape_square,
        [Description("ss_shape_square_add")]
        shape_square_add,
        [Description("ss_shape_square_delete")]
        shape_square_delete,
        [Description("ss_shape_square_edit")]
        shape_square_edit,
        [Description("ss_shape_square_error")]
        shape_square_error,
        [Description("ss_shape_square_go")]
        shape_square_go,
        [Description("ss_shape_square_key")]
        shape_square_key,
        [Description("ss_shape_square_link")]
        shape_square_link,
        [Description("ss_shape_ungroup")]
        shape_ungroup,
        [Description("ss_shield")]
        shield,
        [Description("ss_shield_add")]
        shield_add,
        [Description("ss_shield_delete")]
        shield_delete,
        [Description("ss_shield_go")]
        shield_go,
        [Description("ss_sitemap")]
        sitemap,
        [Description("ss_sitemap_color")]
        sitemap_color,
        [Description("ss_sound")]
        sound,
        [Description("ss_sound_add")]
        sound_add,
        [Description("ss_sound_delete")]
        sound_delete,
        [Description("ss_sound_low")]
        sound_low,
        [Description("ss_sound_mute")]
        sound_mute,
        [Description("ss_sound_none")]
        sound_none,
        [Description("ss_spellcheck")]
        spellcheck,
        [Description("ss_sport_8ball")]
        sport_8ball,
        [Description("ss_sport_basketball")]
        sport_basketball,
        [Description("ss_sport_football")]
        sport_football,
        [Description("ss_sport_golf")]
        sport_golf,
        [Description("ss_sport_raquet")]
        sport_raquet,
        [Description("ss_sport_shuttlecock")]
        sport_shuttlecock,
        [Description("ss_sport_soccer")]
        sport_soccer,
        [Description("ss_sport_tennis")]
        sport_tennis,
        [Description("ss_star")]
        star,
        [Description("ss_status_away")]
        status_away,
        [Description("ss_status_busy")]
        status_busy,
        [Description("ss_status_offline")]
        status_offline,
        [Description("ss_status_online")]
        status_online,
        [Description("ss_stop")]
        stop,
        [Description("ss_style")]
        style,
        [Description("ss_style_add")]
        style_add,
        [Description("ss_style_delete")]
        style_delete,
        [Description("ss_style_edit")]
        style_edit,
        [Description("ss_style_go")]
        style_go,
        [Description("ss_sum")]
        sum,
        [Description("ss_tab")]
        tab,
        [Description("ss_tab_add")]
        tab_add,
        [Description("ss_tab_delete")]
        tab_delete,
        [Description("ss_tab_edit")]
        tab_edit,
        [Description("ss_tab_go")]
        tab_go,
        [Description("ss_table")]
        table,
        [Description("ss_table_add")]
        table_add,
        [Description("ss_table_delete")]
        table_delete,
        [Description("ss_table_edit")]
        table_edit,
        [Description("ss_table_error")]
        table_error,
        [Description("ss_table_gear")]
        table_gear,
        [Description("ss_table_go")]
        table_go,
        [Description("ss_table_key")]
        table_key,
        [Description("ss_table_lightning")]
        table_lightning,
        [Description("ss_table_link")]
        table_link,
        [Description("ss_table_multiple")]
        table_multiple,
        [Description("ss_table_refresh")]
        table_refresh,
        [Description("ss_table_relationship")]
        table_relationship,
        [Description("ss_table_row_delete")]
        table_row_delete,
        [Description("ss_table_row_insert")]
        table_row_insert,
        [Description("ss_table_save")]
        table_save,
        [Description("ss_table_sort")]
        table_sort,
        [Description("ss_tag")]
        tag,
        [Description("ss_tag_blue")]
        tag_blue,
        [Description("ss_tag_blue_add")]
        tag_blue_add,
        [Description("ss_tag_blue_delete")]
        tag_blue_delete,
        [Description("ss_tag_blue_edit")]
        tag_blue_edit,
        [Description("ss_tag_green")]
        tag_green,
        [Description("ss_tag_orange")]
        tag_orange,
        [Description("ss_tag_pink")]
        tag_pink,
        [Description("ss_tag_purple")]
        tag_purple,
        [Description("ss_tag_red")]
        tag_red,
        [Description("ss_tag_yellow")]
        tag_yellow,
        [Description("ss_telephone")]
        telephone,
        [Description("ss_telephone_add")]
        telephone_add,
        [Description("ss_telephone_delete")]
        telephone_delete,
        [Description("ss_telephone_edit")]
        telephone_edit,
        [Description("ss_telephone_error")]
        telephone_error,
        [Description("ss_telephone_go")]
        telephone_go,
        [Description("ss_telephone_key")]
        telephone_key,
        [Description("ss_telephone_link")]
        telephone_link,
        [Description("ss_television")]
        television,
        [Description("ss_television_add")]
        television_add,
        [Description("ss_television_delete")]
        television_delete,
        [Description("ss_text_align_center")]
        text_align_center,
        [Description("ss_text_align_justify")]
        text_align_justify,
        [Description("ss_text_align_left")]
        text_align_left,
        [Description("ss_text_align_right")]
        text_align_right,
        [Description("ss_text_allcaps")]
        text_allcaps,
        [Description("ss_text_bold")]
        text_bold,
        [Description("ss_text_columns")]
        text_columns,
        [Description("ss_text_dropcaps")]
        text_dropcaps,
        [Description("ss_text_heading_1")]
        text_heading_1,
        [Description("ss_text_heading_2")]
        text_heading_2,
        [Description("ss_text_heading_3")]
        text_heading_3,
        [Description("ss_text_heading_4")]
        text_heading_4,
        [Description("ss_text_heading_5")]
        text_heading_5,
        [Description("ss_text_heading_6")]
        text_heading_6,
        [Description("ss_text_horizontalrule")]
        text_horizontalrule,
        [Description("ss_text_indent")]
        text_indent,
        [Description("ss_text_indent_remove")]
        text_indent_remove,
        [Description("ss_text_italic")]
        text_italic,
        [Description("ss_text_kerning")]
        text_kerning,
        [Description("ss_text_letter_omega")]
        text_letter_omega,
        [Description("ss_text_letterspacing")]
        text_letterspacing,
        [Description("ss_text_linespacing")]
        text_linespacing,
        [Description("ss_text_list_bullets")]
        text_list_bullets,
        [Description("ss_text_list_numbers")]
        text_list_numbers,
        [Description("ss_text_lowercase")]
        text_lowercase,
        [Description("ss_text_padding_bottom")]
        text_padding_bottom,
        [Description("ss_text_padding_left")]
        text_padding_left,
        [Description("ss_text_padding_right")]
        text_padding_right,
        [Description("ss_text_padding_top")]
        text_padding_top,
        [Description("ss_text_replace")]
        text_replace,
        [Description("ss_text_signature")]
        text_signature,
        [Description("ss_text_smallcaps")]
        text_smallcaps,
        [Description("ss_text_strikethrough")]
        text_strikethrough,
        [Description("ss_text_subscript")]
        text_subscript,
        [Description("ss_text_superscript")]
        text_superscript,
        [Description("ss_text_underline")]
        text_underline,
        [Description("ss_text_uppercase")]
        text_uppercase,
        [Description("ss_textfield")]
        textfield,
        [Description("ss_textfield_add")]
        textfield_add,
        [Description("ss_textfield_delete")]
        textfield_delete,
        [Description("ss_textfield_key")]
        textfield_key,
        [Description("ss_textfield_rename")]
        textfield_rename,
        [Description("ss_thumb_down")]
        thumb_down,
        [Description("ss_thumb_up")]
        thumb_up,
        [Description("ss_tick")]
        tick,
        [Description("ss_time")]
        time,
        [Description("ss_time_add")]
        time_add,
        [Description("ss_time_delete")]
        time_delete,
        [Description("ss_time_go")]
        time_go,
        [Description("ss_timeline_marker")]
        timeline_marker,
        [Description("ss_transmit")]
        transmit,
        [Description("ss_transmit_add")]
        transmit_add,
        [Description("ss_transmit_blue")]
        transmit_blue,
        [Description("ss_transmit_delete")]
        transmit_delete,
        [Description("ss_transmit_edit")]
        transmit_edit,
        [Description("ss_transmit_error")]
        transmit_error,
        [Description("ss_transmit_go")]
        transmit_go,
        [Description("ss_tux")]
        tux,
        [Description("ss_user")]
        user,
        [Description("ss_user_add")]
        user_add,
        [Description("ss_user_comment")]
        user_comment,
        [Description("ss_user_delete")]
        user_delete,
        [Description("ss_user_edit")]
        user_edit,
        [Description("ss_user_female")]
        user_female,
        [Description("ss_user_go")]
        user_go,
        [Description("ss_user_gray")]
        user_gray,
        [Description("ss_user_green")]
        user_green,
        [Description("ss_user_orange")]
        user_orange,
        [Description("ss_user_red")]
        user_red,
        [Description("ss_user_suit")]
        user_suit,
        [Description("ss_vcard")]
        vcard,
        [Description("ss_vcard_add")]
        vcard_add,
        [Description("ss_vcard_delete")]
        vcard_delete,
        [Description("ss_vcard_edit")]
        vcard_edit,
        [Description("ss_vector")]
        vector,
        [Description("ss_vector_add")]
        vector_add,
        [Description("ss_vector_delete")]
        vector_delete,
        [Description("ss_wand")]
        wand,
        [Description("ss_weather_clouds")]
        weather_clouds,
        [Description("ss_weather_cloudy")]
        weather_cloudy,
        [Description("ss_weather_lightning")]
        weather_lightning,
        [Description("ss_weather_rain")]
        weather_rain,
        [Description("ss_weather_snow")]
        weather_snow,
        [Description("ss_weather_sun")]
        weather_sun,
        [Description("ss_webcam")]
        webcam,
        [Description("ss_webcam_add")]
        webcam_add,
        [Description("ss_webcam_delete")]
        webcam_delete,
        [Description("ss_webcam_error")]
        webcam_error,
        [Description("ss_world")]
        world,
        [Description("ss_world_add")]
        world_add,
        [Description("ss_world_delete")]
        world_delete,
        [Description("ss_world_edit")]
        world_edit,
        [Description("ss_world_go")]
        world_go,
        [Description("ss_world_link")]
        world_link,
        [Description("ss_wrench")]
        wrench,
        [Description("ss_wrench_orange")]
        wrench_orange,
        [Description("ss_xhtml")]
        xhtml,
        [Description("ss_xhtml_add")]
        xhtml_add,
        [Description("ss_xhtml_delete")]
        xhtml_delete,
        [Description("ss_xhtml_go")]
        xhtml_go,
        [Description("ss_xhtml_valid")]
        xhtml_valid,
        [Description("ss_zoom")]
        zoom,
        [Description("ss_zoom_in")]
        zoom_in,
        [Description("ss_zoom_out")]
        zoom_out
    }
    /*
   see sprites/icons.html
   * 
   * Lazy mans enum generator - NOTE : Changed the icons new and locks to title case due to keyword
        var head = document.getElementsByTagName('head')[0];
        var scriptFromGoogle = document.createElement('script');
        scriptFromGoogle .type = "text/javascript";
        scriptFromGoogle .src = 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js';

        head.appendChild(scriptFromGoogle );

        var scriptForEnum = document.createElement('script');
        scriptForEnum.type = "text/javascript";
        scriptForEnum.text = "$('body').append('<div id=\"toAppend\"/>');var $div = $(\"#toAppend\");var html = new Array();var description = '[Description(\"NAME\")]';var name = '<br/>NAME,<br/>';$('.ss_sprite').each(function(){var current = $(this).attr('class').replace(\"ss_sprite \", \"\");var currentDescription = description.replace(\"NAME\",current);var currentEnumElement = name.replace(\"NAME\",current.replace(\"ss_\", \"\"));html.push(currentDescription + currentEnumElement);});$div.html(html.join(''));";
        head.appendChild(scriptForEnum );
   */
    public class FamFamSpritesIconAndButtonsRepository : IconsAndButtonsBase<FamFamSpritesEnum>
    {
        internal override string IconBaseCSSClassRtl
        {
            get { return "ss_sprite"; }
        }
        internal override string IconBaseCSSClassLtr
        {
            get { return "ss_sprite"; }
        }
    }
}
