using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;

namespace MVCUIHelpers.IconsAndButtons.jQueryUI
{
    public enum jQueryUIIconsEnum
    {
        [Description("ui-icon-carat-1-n")]
        carat_1_n,
        [Description("ui-icon-carat-1-ne")]
        carat_1_ne,
        [Description("ui-icon-carat-1-e")]
        carat_1_e,
        [Description("ui-icon-carat-1-se")]
        carat_1_se,
        [Description("ui-icon-carat-1-s")]
        carat_1_s,
        [Description("ui-icon-carat-1-sw")]
        carat_1_sw,
        [Description("ui-icon-carat-1-w")]
        carat_1_w,
        [Description("ui-icon-carat-1-nw")]
        carat_1_nw,
        [Description("ui-icon-carat-2-n-s")]
        carat_2_n_s,
        [Description("ui-icon-carat-2-e-w")]
        carat_2_e_w,
        [Description("ui-icon-triangle-1-n")]
        triangle_1_n,
        [Description("ui-icon-triangle-1-ne")]
        triangle_1_ne,
        [Description("ui-icon-triangle-1-e")]
        triangle_1_e,
        [Description("ui-icon-triangle-1-se")]
        triangle_1_se,
        [Description("ui-icon-triangle-1-s")]
        triangle_1_s,
        [Description("ui-icon-triangle-1-sw")]
        triangle_1_sw,
        [Description("ui-icon-triangle-1-w")]
        triangle_1_w,
        [Description("ui-icon-triangle-1-nw")]
        triangle_1_nw,
        [Description("ui-icon-triangle-2-n-s")]
        triangle_2_n_s,
        [Description("ui-icon-triangle-2-e-w")]
        triangle_2_e_w,
        [Description("ui-icon-arrow-1-n")]
        arrow_1_n,
        [Description("ui-icon-arrow-1-ne")]
        arrow_1_ne,
        [Description("ui-icon-arrow-1-e")]
        arrow_1_e,
        [Description("ui-icon-arrow-1-se")]
        arrow_1_se,
        [Description("ui-icon-arrow-1-s")]
        arrow_1_s,
        [Description("ui-icon-arrow-1-sw")]
        arrow_1_sw,
        [Description("ui-icon-arrow-1-w")]
        arrow_1_w,
        [Description("ui-icon-arrow-1-nw")]
        arrow_1_nw,
        [Description("ui-icon-arrow-2-n-s")]
        arrow_2_n_s,
        [Description("ui-icon-arrow-2-ne-sw")]
        arrow_2_ne_sw,
        [Description("ui-icon-arrow-2-e-w")]
        arrow_2_e_w,
        [Description("ui-icon-arrow-2-se-nw")]
        arrow_2_se_nw,
        [Description("ui-icon-arrowstop-1-n")]
        arrowstop_1_n,
        [Description("ui-icon-arrowstop-1-e")]
        arrowstop_1_e,
        [Description("ui-icon-arrowstop-1-s")]
        arrowstop_1_s,
        [Description("ui-icon-arrowstop-1-w")]
        arrowstop_1_w,
        [Description("ui-icon-arrowthick-1-n")]
        arrowthick_1_n,
        [Description("ui-icon-arrowthick-1-ne")]
        arrowthick_1_ne,
        [Description("ui-icon-arrowthick-1-e")]
        arrowthick_1_e,
        [Description("ui-icon-arrowthick-1-se")]
        arrowthick_1_se,
        [Description("ui-icon-arrowthick-1-s")]
        arrowthick_1_s,
        [Description("ui-icon-arrowthick-1-sw")]
        arrowthick_1_sw,
        [Description("ui-icon-arrowthick-1-w")]
        arrowthick_1_w,
        [Description("ui-icon-arrowthick-1-nw")]
        arrowthick_1_nw,
        [Description("ui-icon-arrowthick-2-n-s")]
        arrowthick_2_n_s,
        [Description("ui-icon-arrowthick-2-ne-sw")]
        arrowthick_2_ne_sw,
        [Description("ui-icon-arrowthick-2-e-w")]
        arrowthick_2_e_w,
        [Description("ui-icon-arrowthick-2-se-nw")]
        arrowthick_2_se_nw,
        [Description("ui-icon-arrowthickstop-1-n")]
        arrowthickstop_1_n,
        [Description("ui-icon-arrowthickstop-1-e")]
        arrowthickstop_1_e,
        [Description("ui-icon-arrowthickstop-1-s")]
        arrowthickstop_1_s,
        [Description("ui-icon-arrowthickstop-1-w")]
        arrowthickstop_1_w,
        [Description("ui-icon-arrowreturnthick-1-w")]
        arrowreturnthick_1_w,
        [Description("ui-icon-arrowreturnthick-1-n")]
        arrowreturnthick_1_n,
        [Description("ui-icon-arrowreturnthick-1-e")]
        arrowreturnthick_1_e,
        [Description("ui-icon-arrowreturnthick-1-s")]
        arrowreturnthick_1_s,
        [Description("ui-icon-arrowreturn-1-w")]
        arrowreturn_1_w,
        [Description("ui-icon-arrowreturn-1-n")]
        arrowreturn_1_n,
        [Description("ui-icon-arrowreturn-1-e")]
        arrowreturn_1_e,
        [Description("ui-icon-arrowreturn-1-s")]
        arrowreturn_1_s,
        [Description("ui-icon-arrowrefresh-1-w")]
        arrowrefresh_1_w,
        [Description("ui-icon-arrowrefresh-1-n")]
        arrowrefresh_1_n,
        [Description("ui-icon-arrowrefresh-1-e")]
        arrowrefresh_1_e,
        [Description("ui-icon-arrowrefresh-1-s")]
        arrowrefresh_1_s,
        [Description("ui-icon-arrow-4")]
        arrow_4,
        [Description("ui-icon-arrow-4-diag")]
        arrow_4_diag,
        [Description("ui-icon-extlink")]
        extlink,
        [Description("ui-icon-newwin")]
        newwin,
        [Description("ui-icon-refresh")]
        refresh,
        [Description("ui-icon-shuffle")]
        shuffle,
        [Description("ui-icon-transfer-e-w")]
        transfer_e_w,
        [Description("ui-icon-transferthick-e-w")]
        transferthick_e_w,
        [Description("ui-icon-folder-collapsed")]
        folder_collapsed,
        [Description("ui-icon-folder-open")]
        folder_open,
        [Description("ui-icon-document")]
        document,
        [Description("ui-icon-document-b")]
        document_b,
        [Description("ui-icon-note")]
        note,
        [Description("ui-icon-mail-closed")]
        mail_closed,
        [Description("ui-icon-mail-open")]
        mail_open,
        [Description("ui-icon-suitcase")]
        suitcase,
        [Description("ui-icon-comment")]
        comment,
        [Description("ui-icon-person")]
        person,
        [Description("ui-icon-print")]
        print,
        [Description("ui-icon-trash")]
        trash,
        [Description("ui-icon-locked")]
        locked,
        [Description("ui-icon-unlocked")]
        unlocked,
        [Description("ui-icon-bookmark")]
        bookmark,
        [Description("ui-icon-tag")]
        tag,
        [Description("ui-icon-home")]
        home,
        [Description("ui-icon-flag")]
        flag,
        [Description("ui-icon-calculator")]
        calculator,
        [Description("ui-icon-cart")]
        cart,
        [Description("ui-icon-pencil")]
        pencil,
        [Description("ui-icon-clock")]
        clock,
        [Description("ui-icon-disk")]
        disk,
        [Description("ui-icon-calendar")]
        calendar,
        [Description("ui-icon-zoomin")]
        zoomin,
        [Description("ui-icon-zoomout")]
        zoomout,
        [Description("ui-icon-search")]
        search,
        [Description("ui-icon-wrench")]
        wrench,
        [Description("ui-icon-gear")]
        gear,
        [Description("ui-icon-heart")]
        heart,
        [Description("ui-icon-star")]
        star,
        [Description("ui-icon-link")]
        link,
        [Description("ui-icon-cancel")]
        cancel,
        [Description("ui-icon-plus")]
        plus,
        [Description("ui-icon-plusthick")]
        plusthick,
        [Description("ui-icon-minus")]
        minus,
        [Description("ui-icon-minusthick")]
        minusthick,
        [Description("ui-icon-close")]
        close,
        [Description("ui-icon-closethick")]
        closethick,
        [Description("ui-icon-key")]
        key,
        [Description("ui-icon-lightbulb")]
        lightbulb,
        [Description("ui-icon-scissors")]
        scissors,
        [Description("ui-icon-clipboard")]
        clipboard,
        [Description("ui-icon-copy")]
        copy,
        [Description("ui-icon-contact")]
        contact,
        [Description("ui-icon-image")]
        image,
        [Description("ui-icon-video")]
        video,
        [Description("ui-icon-script")]
        script,
        [Description("ui-icon-alert")]
        alert,
        [Description("ui-icon-info")]
        info,
        [Description("ui-icon-notice")]
        notice,
        [Description("ui-icon-help")]
        help,
        [Description("ui-icon-check")]
        check,
        [Description("ui-icon-bullet")]
        bullet,
        [Description("ui-icon-radio-off")]
        radio_off,
        [Description("ui-icon-radio-on")]
        radio_on,
        [Description("ui-icon-pin-w")]
        pin_w,
        [Description("ui-icon-pin-s")]
        pin_s,
        [Description("ui-icon-play")]
        play,
        [Description("ui-icon-pause")]
        pause,
        [Description("ui-icon-seek-next")]
        seek_next,
        [Description("ui-icon-seek-prev")]
        seek_prev,
        [Description("ui-icon-seek-end")]
        seek_end,
        [Description("ui-icon-seek-first")]
        seek_first,
        [Description("ui-icon-stop")]
        stop,
        [Description("ui-icon-eject")]
        eject,
        [Description("ui-icon-volume-off")]
        volume_off,
        [Description("ui-icon-volume-on")]
        volume_on,
        [Description("ui-icon-power")]
        power,
        [Description("ui-icon-signal-diag")]
        signal_diag,
        [Description("ui-icon-signal")]
        signal,
        [Description("ui-icon-battery-0")]
        battery_0,
        [Description("ui-icon-battery-1")]
        battery_1,
        [Description("ui-icon-battery-2")]
        battery_2,
        [Description("ui-icon-battery-3")]
        battery_3,
        [Description("ui-icon-circle-plus")]
        circle_plus,
        [Description("ui-icon-circle-minus")]
        circle_minus,
        [Description("ui-icon-circle-close")]
        circle_close,
        [Description("ui-icon-circle-triangle-e")]
        circle_triangle_e,
        [Description("ui-icon-circle-triangle-s")]
        circle_triangle_s,
        [Description("ui-icon-circle-triangle-w")]
        circle_triangle_w,
        [Description("ui-icon-circle-triangle-n")]
        circle_triangle_n,
        [Description("ui-icon-circle-arrow-e")]
        circle_arrow_e,
        [Description("ui-icon-circle-arrow-s")]
        circle_arrow_s,
        [Description("ui-icon-circle-arrow-w")]
        circle_arrow_w,
        [Description("ui-icon-circle-arrow-n")]
        circle_arrow_n,
        [Description("ui-icon-circle-zoomin")]
        circle_zoomin,
        [Description("ui-icon-circle-zoomout")]
        circle_zoomout,
        [Description("ui-icon-circle-check")]
        circle_check,
        [Description("ui-icon-circlesmall-plus")]
        circlesmall_plus,
        [Description("ui-icon-circlesmall-minus")]
        circlesmall_minus,
        [Description("ui-icon-circlesmall-close")]
        circlesmall_close,
        [Description("ui-icon-squaresmall-plus")]
        squaresmall_plus,
        [Description("ui-icon-squaresmall-minus")]
        squaresmall_minus,
        [Description("ui-icon-squaresmall-close")]
        squaresmall_close,
        [Description("ui-icon-grip-dotted-vertical")]
        grip_dotted_vertical,
        [Description("ui-icon-grip-dotted-horizontal")]
        grip_dotted_horizontal,
        [Description("ui-icon-grip-solid-vertical")]
        grip_solid_vertical,
        [Description("ui-icon-grip-solid-horizontal")]
        grip_solid_horizontal,
        [Description("ui-icon-gripsmall-diagonal-se")]
        gripsmall_diagonal_se,
        [Description("ui-icon-grip-diagonal-se")]
        grip_diagonal_se
    }
    /*
     http://jquery-ui.googlecode.com/svn/trunk/tests/static/icons.html
     * 
     * Lazy mans enum generator
        $('body').append('<div id="toAppend"/>');
        var $div = $("#toAppend");
        var html = new Array();
        var description = '[Description("NAME")]';
        var name = '<br/>NAME,<br/>';
        $('.ui-icon').each(function(){
            var current = $(this).attr('class').replace("ui-icon ", "");
            var currentDescription = description.replace("NAME",current);
            var currentEnumElement = name.replace("NAME",current.replace("ui-icon-", "").replace(/\-/g,"_"));
        html.push(currentDescription + currentEnumElement);
        });
        $div.html(html.join(''));
     */
    public class jQueryUIIconsAndButtonsRepository : IconsAndButtonsBase<jQueryUIIconsEnum>
    {
        internal override string IconBaseCSSClassLtr
        {
            get { return "ui-icon ui-icon-helper-ltr"; }
        }
        internal override string IconBaseCSSClassRtl
        {
            get { return "ui-icon ui-icon-helper-rtl"; }
        }
    }
}
